#!/usr/bin/env python3
"""
Json Placeholder Scheduler Agent Intelligence Agent — Scheduler Agent
Auto-generated by Agent Builder. DO NOT edit manually.

Trigger: schedule
Jobs: 1
Timezone: Asia/Kolkata
DB: firestore / scheduler_data
Memory TTL: 24h
"""

import os
import json
import logging
from datetime import datetime
from contextlib import asynccontextmanager

import httpx
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger
import pytz
from cachetools import TTLCache

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)

# ── Timezone ─────────────────────────────────────────────────────────────────
tz = pytz.timezone('Asia/Kolkata')

# ── In-memory cache (TTL=24h) ──────────────────────────────────────
_cache = TTLCache(maxsize=500, ttl=86400)

# ── Firestore / DB ────────────────────────────────────────────────────────────
try:
    from google.cloud import firestore as _firestore
    _db = _firestore.Client(project=os.getenv("GOOGLE_CLOUD_PROJECT", 'gen-ai-poc-onboarding'))
    logger.info("Firestore client initialized")
except Exception as _e:
    _db = None
    logger.warning("Firestore unavailable: %s", _e)

# ── LLM ──────────────────────────────────────────────────────────────────────
try:
    import vertexai
    from vertexai.generative_models import GenerativeModel
    vertexai.init(project=os.getenv("GOOGLE_CLOUD_PROJECT", "gen-ai-poc-onboarding"),
                  location=os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1"))
    _llm = GenerativeModel(os.getenv("LLM_MODEL", 'gemini-2.5-flash'))
except Exception as _e:
    _llm = None
    logger.warning("LLM unavailable: %s", _e)

SYSTEM_PROMPT = """You are a helpful scheduler agent."""

# ─── Scheduled Job Functions ──────────────────────────────────────────────────

def job_1():
    """Scheduled job: Json Place holder data — GET https://json-placeholder.mock.beeceptor.com/posts"""
    label = 'Json Place holder data'
    url   = 'https://json-placeholder.mock.beeceptor.com/posts'
    logger.info("[%s] Running scheduled fetch: %s %s", label, 'GET', url)
    headers = {}
    body = None
    pass  # no auth

    try:
        with httpx.Client() as client:
            response = client.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        try:
            data = response.json()
        except Exception:
            data = {"raw": response.text}
        logger.info("[%s] Fetch OK — HTTP %s", label, response.status_code)
        record = {
            "jobName":   'Json Place holder data',
            "url":       url,
            "method":    'GET',
            "fetchedAt": datetime.utcnow().isoformat() + "Z",
            "data":      data,
            "httpStatus": response.status_code,
        }
        if _db:
            _db.collection('JSON-placeholder-data').add(record)
            logger.info("[%s] Saved to Firestore collection '%s'", 'Json Place holder data', 'JSON-placeholder-data')
        # Also cache in memory
        _cache['job_1'] = record
    except httpx.TimeoutException:
        logger.error("[%s] Request timed out: %s", label, url)
    except httpx.HTTPStatusError as exc:
        logger.error("[%s] HTTP error %s: %s", label, exc.response.status_code, url)
    except Exception as exc:
        logger.exception("[%s] Unexpected error: %s", label, exc)


# ─── APScheduler Setup ────────────────────────────────────────────────────────
scheduler = BackgroundScheduler(timezone=tz)

def _register_jobs():
    scheduler.add_job(job_1, CronTrigger(hour=12, minute=40, timezone=tz), id='job_1_12:40', replace_existing=True, name='Json Place holder data @ 12:40')
    scheduler.add_job(job_1, CronTrigger(hour=17, minute=1, timezone=tz), id='job_1_17:01', replace_existing=True, name='Json Place holder data @ 17:01')
    logger.info("Registered %d scheduled job(s)", len(scheduler.get_jobs()))

# ─── FastAPI Lifespan ─────────────────────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    _register_jobs()
    scheduler.start()
    logger.info("Scheduler started. Next run times:")
    for job in scheduler.get_jobs():
        logger.info("  %s — next: %s", job.name, job.next_run_time)
    yield
    scheduler.shutdown(wait=False)
    logger.info("Scheduler stopped.")

app = FastAPI(title='Json Placeholder Scheduler Agent Intelligence Agent', lifespan=lifespan)
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# ─── Request / Response Models ────────────────────────────────────────────────
class ChatRequest(BaseModel):
    message: str
    session_id: str = "default"

class RunResponse(BaseModel):
    triggered: int
    message: str

# ─── Endpoints ────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {
        "status": "ok",
        "agent": 'Json Placeholder Scheduler Agent Intelligence Agent',
        "scheduler_running": scheduler.running,
        "jobs": len(scheduler.get_jobs()),
        "cached_results": len(_cache),
    }

@app.get("/scheduler/status")
def scheduler_status():
    """Return status of all scheduled jobs with next run times and last cached result."""
    jobs_info = []
    for job in scheduler.get_jobs():
        jobs_info.append({
            "id": job.id,
            "name": job.name,
            "next_run": str(job.next_run_time) if job.next_run_time else None,
            "cached_result": _cache.get(job.id.rsplit("_", 1)[0]),
        })
    return {
        "timezone": 'Asia/Kolkata',
        "db_target": 'firestore',
        "memory_ttl_hours": 24,
        "jobs": jobs_info,
    }

@app.post("/run")
def run_all_jobs():
    """Manually trigger all enabled jobs immediately (for testing)."""
    triggered = 0
    errors = []
    job_fns = [job_1]
    for fn in job_fns:
        try:
            fn()
            triggered += 1
        except Exception as e:
            errors.append(str(e))
    return RunResponse(
        triggered=triggered,
        message=f"Triggered {triggered} job(s)." + (f" Errors: {'; '.join(errors)}" if errors else "")
    )

@app.post("/chat")
async def chat(request: ChatRequest):
    """Chat with the agent. It uses cached scheduler results as context."""
    # Build context from cached job results
    context_parts = []
    for key, val in _cache.items():
        if isinstance(val, dict):
            fetched_at = val.get("fetchedAt", "unknown time")
            data_preview = json.dumps(val.get("data", {}), default=str)[:1000]
            context_parts.append(f"[{val.get('jobName','job')} @ {fetched_at}]: {data_preview}")

    context = "\n\n".join(context_parts) if context_parts else "No data fetched yet."
    full_prompt = f"{SYSTEM_PROMPT}\n\nLatest fetched data:\n{context}\n\nUser: {request.message}"

    if _llm:
        try:
            response = _llm.generate_content(full_prompt)
            reply = response.text
        except Exception as e:
            logger.error("LLM error: %s", e)
            reply = f"I have data from {len(_cache)} source(s) but the LLM is unavailable: {e}"
    else:
        reply = f"Scheduler is running. I have {len(_cache)} cached result(s). LLM not available."

    return {"response": reply, "session_id": request.session_id, "cached_sources": len(_cache)}